define:
  - &subreddit-settings
    type: reddit
    collapse-after: 3
    show-thumbnails: true
    style: vertical-list
    show-flairs: true
    cache: 2h
    limit: 10


server:
  assets-path: /app/assets

theme:
  background-color: 0 0 16
  primary-color: 43 59 81
  positive-color: 61 66 44
  negative-color: 6 96 59
  custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: news.yml
  - $include: reddit.yml
