- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: releases
          cache: 1d
          show-source-icon: true
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          token: ${GIT_PAT_TOKEN}
          repositories:
            - glanceapp/glance
            - immich-app/immich
            - dani-garcia/vaultwarden

        - type: server-stats
          hide-header: true
          servers:
            - type: local
              name: HP-Docker
              hide-mountpoints-by-default: true
              mountpoints:
                "/app/config":
                  hide: false
                  name: "Host"
            - type: remote
              name: Alpine LXC
              url: ${ALPINE_URL}
              token: ${MY_SECRET_TOKEN}

        - type: calendar
          hide-header: true
          first-day-of-week: monday

        # - type: rss
        #   limit: 10
        #   collapse-after: 3
        #   cache: 12h
        #   feeds:
        #     - url: https://selfh.st/rss/
        #       title: selfh.st
        #     - url: https://ciechanow.ski/atom.xml
        #     - url: https://www.joshwcomeau.com/rss.xml
        #       title: Josh Comeau
        #     - url: https://samwho.dev/rss.xml
        #     - url: https://ishadeed.com/feed.xml
        #       title: Ahmad Shadeed

        # - type: twitch-channels
        #   channels:
        #     - theprimeagen
        #     - j_blow
        #     - piratesoftware
        #     - cohhcarnage
        #     - christitustech
        #     - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:            
            - type: lobsters
              sort-by: hot
              tags:
                - linux
              limit: 15
            - type: hacker-news
              limit: 15
              collapse-after: 3

        - type: docker-containers
          hide-by-default: false
          title: Containers

        - type: group
          widgets:
          - type: videos
            cache: 30m
            style: grid-cards
            # collapse-after: 10
            limit: 30
            collapse-after-rows: 2
            include-shorts: true
            channels:
              - UC_0CVCfC_3iuHqmyClu59Uw # ETA Prime
              - UCdBK94H6oZT2Q7l0-b0xmMg # Short Circuit
              - UCg6gPGh8HU2U01vaFCAsvmQ # ChrisTitusTech
              - UCeeFfhMcJa1kjtfZAGskOCA # Tech Linked
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim
              - UCO2x-p9gg9TLKneXlibGR7w # Snazzy Labs
              - UCWFKCr40YwOZQx8FHU_ZqqQ # JerryRigEverything
              - UCgdTVe88YVSrOZ9qKumhULQ # Hardware Haven
              - UC9evhW4JB_UdXSLeZGy8lGw # Raid Owl
              - UCwFpzG5MK5Shg_ncAhrgr9g # Awesome Self-Hosted
              - UC5UAwBUum7CPN5buc-_N1Fw # The Linux Experiment
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCueOZEvMffxjJyVO1fGiJNQ # ZiggoSport
          - type: videos
            cache: 30m
            style: grid-cards
            # collapse-after: 10
            limit: 30
            collapse-after-rows: 2
            include-shorts: true
            title: Playlist
            playlists:
            - PLQ6aZBKP-rxlUheWxexunIVNcS2Fn__DV # Add your playlist ID, set it to unlisted, set it to add new videos to the top

        # - type: group
        #   widgets:
        #     - type: reddit
        #       subreddit: selfhosted
        #       show-thumbnails: true
        #     - type: reddit
        #       subreddit: homelab
        #       show-thumbnails: true
        #     - type: reddit
        #       subreddit: raspberry_pi
        #       show-thumbnails: true
        #     - type: reddit
        #       subreddit: unixporn
        #       show-thumbnails: true

    - size: small
      widgets:
        - type: search
          search-engine: google
          new-tab: true
          autofocus: true
          bangs:
            - title: GitHub
              shortcut: "!gh"
              url: https://github.com/search?q={QUERY}&type=repositories

            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}

            - title: SimpleIcons
              shortcut: "!si"
              url: https://simpleicons.org/?q={QUERY}

        - type: custom-api
          title: Proxmox Stats
          cache: 1m
          url: https://${PROXMOXVE_URL}/api2/json/cluster/resources
          allow-insecure: true
          headers:
            Accept: application/json
            Authorization: PVEAPIToken=${PROXMOXVE_KEY}
          template: |
            <div class="flex flex-column gap-5">
              <div class="flex justify-between text-center">
                <div>
                  {{ $nodes_online := len (.JSON.Array "data.#(type==\"node\")#|#(status==\"online\")#") }}
                  {{ $nodes_total := len (.JSON.Array "data.#(type==\"node\")#") }}
                  <div class="color-highlight size-h3">{{ $nodes_online }}/{{ $nodes_total }}</div>
                  <div class="size-h5 uppercase">Node</div>
                </div>
                <div>
                  {{ $lxc_running := len (.JSON.Array "data.#(type==\"lxc\")#|#(status==\"running\")#|#(template==0)#") }}
                  {{ $lxc_total := len (.JSON.Array "data.#(type==\"lxc\")#|#(template==0)#") }}
                  <div class="color-highlight size-h3">{{ $lxc_running }}/{{ $lxc_total }}</div>
                  <div class="size-h5 uppercase">LXC</div>
                </div>
                <div>
                  {{ $qemu_running := len (.JSON.Array "data.#(type==\"qemu\")#|#(status==\"running\")#|#(template==0)#") }}
                  {{ $qemu_total := len (.JSON.Array "data.#(type==\"qemu\")#|#(template==0)#") }}
                  <div class="color-highlight size-h3">{{ $qemu_running }}/{{ $qemu_total }}</div>
                  <div class="size-h5 uppercase">VM</div>
                </div>
                <div>
                    {{ $storage_available := len (.JSON.Array "data.#(type==\"storage\")#|#(status==\"available\")#") }}
                    {{ $storage_total := len (.JSON.Array "data.#(type==\"storage\")#") }}
                    <div class="color-highlight size-h3">{{ $storage_available }}/{{ $storage_total }}</div>
                    <div class="size-h5 uppercase">Storage</div>
                </div>
              </div>
            </div>

        - type: custom-api
          title: Immich stats
          cache: 1h
          url: ${IMMICH_URL}/api/server/statistics
          headers:
            x-api-key: ${IMMICH_API_KEY}
            Accept: application/json
          template: |
            <div class="flex justify-between text-center">
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "photos" | formatNumber }}</div>
                  <div class="size-h6">PHOTOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ .JSON.Int "videos" | formatNumber }}</div>
                  <div class="size-h6">VIDEOS</div>
              </div>
              <div>
                  <div class="color-highlight size-h3">{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
                  <div class="size-h6">USAGE</div>
              </div>
            </div>
        # - type: clock
        #   hour-format: 12h
        #   timezones:
        #     - timezone: Asia/Kolkata
        #       label: India
        #     - timezone: America/New_York
        #       label: New York
        #     - timezone: Asia/Tokyo
        #       label: Tokyo

        - type: weather
          location: Maastricht
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
           # Optionally hide the location from being displayed in the widget
           # hide-location: true

        - type: group
          widgets:
          - type: monitor
            allow-insecure: true
            cache: 1m
            title: Media Apps
            # style: compact
            sites:
              - title: Immich
                url: ${IMMICH_URL}
                icon: di:immich
              - title: Sonarr
                url: ${SONARR_URL}
                icon: di:sonarr
              - title: Bazarr
                url: ${BAZARR_URL}
                icon: di:bazarr
              - title: Radarr
                url: ${RADARR_URL}
                icon: di:radarr
              - title: Prowlarr
                url: ${PROWLARR_URL}
                icon: di:prowlarr
              - title: QBittorrent
                url: ${QBIT_URL}
                icon: di:qbittorrent
              - title: Jellyfin
                url: ${JELLYFIN_URL}
                icon: di:jellyfin

          - type: monitor
            # allow-insecure: true
            cache: 1m
            title: Productivity Apps
            # style: compact
            sites:
              #- title: Gitea
              #  url: https://gitea.domain.com
              #  icon: di:gitea
              #- title: AdGuard Home
              #  url: http://holyfox.local:85
              #  icon: di:adguard-home
              #- title: Hoarder
              #  url: https://bookmark.domain.com/
              #  icon: di:hoarder-light
              #- title: Gotify
              #  url: https://bookmark.domain.com/
              #  icon: di:gotify
              #- title: Grafana
              #  url: https://hs6.domain.com/grafana/
              #  icon: di:grafana
              #- title: Code Server
              #  url: https://code.hs.domain.com/
              #  icon: di:code
              #- title: Prometheus
              #  url: https://hs6.domain.com/prometheus
              #  icon: di:prometheus
              #  alt-status-codes:
              #    - 403
              #    - 401
              #- title: Vaultwarden
              #  url: https://hs6.domain.com/vaultwarden
              #  icon: di:vaultwarden-light



        # - type: markets
        #   # The link to go to when clicking on the symbol in the UI,
        #   # {SYMBOL} will be substituded with the symbol for each market
        #   symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
        #   markets:
        #     - symbol: SPY
        #       name: S&P 500
        #     - symbol: BTC-USD
        #       name: Bitcoin
        #     - symbol: NVDA
        #       name: NVIDIA
        #     - symbol: AAPL
        #       name: Apple
        #     - symbol: MSFT
        #       name: Microsoft
